import Head from 'next/head';

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>PineDelo's Work</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>{children}</div>
    </>
  );
};

export default Layout;
